version: '3.9'

services:
  db:
    image: postgres:17
    container_name: myapp-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: myapp-backend
    environment:
      DATABASE_URL: postgres://myuser:mypass@db:5432/mydb
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: myapp-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
