services:
  backend:
    build:
      context: ./backend
    container_name: myapp-backend
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: myapp-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
