name: Build and Test

on:
  push:
    branches: [ ci-final ]
  pull_request:
    branches: [ ci-final ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set environment variables
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/mydb" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=myuser" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=mypass" >> $GITHUB_ENV

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.override.yml up -d --build


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Maven tests
        working-directory: ./backend
        run: mvn verify

      - name: Stop Docker Compose
        if: always()
        run: docker compose -f docker-compose.override.yml down
