name: Java CI with Maven, JaCoCo and Coverage Enforcement

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 23
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '23'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/backend/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Change to backend directory
      run: cd backend

    - name: Build with Maven
      run: mvn clean install --no-transfer-progress

    - name: Run Tests with Coverage
      run: mvn test jacoco:report

    - name: Check Coverage
      id: coverage
      run: |
        coverage=$(mvn jacoco:report | grep -oP 'Coverage: \K[0-9]+')
        echo "Coverage is: $coverage%"
        if [ "$coverage" -lt 85 ]; then
          echo "❌ Coverage is below 85%. Failing build."
          exit 1
        else
          echo "✅ Coverage is sufficient."
        fi

    - name: Comment Coverage on PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: coverage
        message: |
          ### 🧪 Code Coverage Report
          - Coverage: **${{ steps.coverage.outputs.coverage }}%**
          - Required: **85%**
