name: Build and Test with Docker Compose

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose version

      - name: Build and run Docker Compose
        run: docker-compose up --build -d

      - name: Wait for services to initialize
        run: sleep 20

      - name: Run basic health checks
        run: echo "Mock health check"

      - name: Shut down
        run: docker-compose down
