name: Build Docker Images as Artifacts

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend Docker image
        run: |
          docker build -t myapp-backend:latest ./backend

      - name: Save backend image as tar
        run: |
          docker save myapp-backend:latest -o backend-image.tar

      - name: Upload backend image artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-docker-image
          path: backend-image.tar

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build frontend Docker image
        run: |
          docker build -t myapp-frontend:latest ./frontend

      - name: Save frontend image as tar
        run: |
          docker save myapp-frontend:latest -o frontend-image.tar

      - name: Upload frontend image artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-docker-image
          path: frontend-image.tar
  build-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build database Docker image
        run: |
          docker build -t myapp-db:latest ./backend/db

      - name: Save database image as tar
        run: |
          docker save myapp-db:latest -o db-image.tar

      - name: Upload database image artifact
        uses: actions/upload-artifact@v3
        with:
          name: db-docker-image
          path: db-image.tar
