CREATE TABLE continents (id SERIAL PRIMARY KEY,name VARCHAR(100) UNIQUE);

CREATE TABLE countries (id SERIAL PRIMARY KEY,name VARCHAR(100) NOT NULL,code VARCHAR(10),continent INT REFERENCES continents(id));

CREATE TABLE cities (id SERIAL PRIMARY KEY,name VARCHAR(100) NOT NULL,country INT REFERENCES countries(id),capital BOOLEAN,latitude DOUBLE PRECISION,longitude DOUBLE PRECISION);